apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  config.yaml: |
    subscriptions:
      - slack:
          - argocd-updates
    triggers:
      - trigger.on-sync-succeeded
      - trigger.on-deployed
